//! Task-related entity definitions.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Status of a UnitTask.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UnitTaskStatus {
    /// Task is waiting to be picked up.
    Queued,
    /// AI is actively working on the task.
    InProgress,
    /// Task requires human action before proceeding.
    ActionRequired,
    /// Task is blocked waiting on an external dependency.
    Blocked,
    /// Task has been completed successfully.
    Completed,
    /// Task execution failed.
    Failed,
    /// Task was cancelled by the user.
    Cancelled,
}

/// Type of subtask that defines the work to be performed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SubTaskType {
    /// Initial implementation of the task.
    InitialImplementation,
    /// Addressing review feedback and making requested changes.
    RequestChanges,
    /// Creating a pull request for the completed work.
    PrCreate,
    /// Fixing issues raised during PR review.
    PrReviewFix,
    /// Fixing CI failures on the PR.
    PrCiFix,
    /// Manually retrying a failed subtask.
    ManualRetry,
}

/// Status of a SubTask.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SubTaskStatus {
    /// Subtask is waiting to be executed.
    Queued,
    /// Subtask is currently being executed.
    InProgress,
    /// Subtask is waiting for user approval of the generated plan.
    WaitingForPlanApproval,
    /// Subtask is waiting for user input to continue.
    WaitingForUserInput,
    /// Subtask has been completed successfully.
    Completed,
    /// Subtask execution failed.
    Failed,
    /// Subtask was cancelled.
    Cancelled,
}

/// Type of action required from the user.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionType {
    /// A PR review has been requested.
    ReviewRequested,
    /// The PR is ready to be created.
    PrCreationReady,
    /// A generated plan requires user approval.
    PlanApprovalRequired,
    /// CI has failed and requires attention.
    CiFailed,
    /// There is a merge conflict that needs to be resolved.
    MergeConflict,
    /// A security alert has been triggered.
    SecurityAlert,
    /// The agent is waiting for user input.
    UserInputRequired,
}

/// A git commit generated by an agent session.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedCommit {
    /// The commit SHA.
    pub sha: String,
    /// Parent commit SHAs.
    pub parent_shas: Vec<String>,
    /// Commit title (first line of commit message).
    pub title: String,
    /// Optional commit body (rest of commit message).
    pub body: Option<String>,
    /// When this commit was authored.
    pub authored_at: DateTime<Utc>,
}

/// A single user-visible task unit.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnitTask {
    /// Unique identifier.
    pub id: Uuid,
    /// Associated workspace ID.
    pub workspace_id: Uuid,
    /// Associated repository group ID.
    pub repository_group_id: Uuid,
    /// Human-readable task title.
    pub title: String,
    /// Full task prompt from the user.
    pub prompt: String,
    /// Custom branch name to use for this task.
    pub branch_name: Option<String>,
    /// Current status of this task.
    pub status: UnitTaskStatus,
    /// Action types that currently require user attention.
    pub action_types: Vec<ActionType>,
    /// IDs of pull request tracking records associated with this task.
    pub pr_tracking_ids: Vec<Uuid>,
    /// The latest commit SHA produced by agent work.
    pub latest_commit_sha: Option<String>,
    /// Total number of commits generated across all subtasks.
    pub generated_commit_count: u32,
    /// Latest patch ref for storing uncommitted changes.
    pub latest_patch_ref: Option<String>,
    /// When this record was created.
    pub created_at: DateTime<Utc>,
    /// When this record was last updated.
    pub updated_at: DateTime<Utc>,
}

impl UnitTask {
    /// Creates a new unit task.
    pub fn new(
        workspace_id: Uuid,
        repository_group_id: Uuid,
        title: impl Into<String>,
        prompt: impl Into<String>,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            workspace_id,
            repository_group_id,
            title: title.into(),
            prompt: prompt.into(),
            branch_name: None,
            status: UnitTaskStatus::Queued,
            action_types: Vec::new(),
            pr_tracking_ids: Vec::new(),
            latest_commit_sha: None,
            generated_commit_count: 0,
            latest_patch_ref: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Sets the branch name for this task.
    pub fn with_branch_name(mut self, branch_name: impl Into<String>) -> Self {
        self.branch_name = Some(branch_name.into());
        self
    }
}

/// A subtask representing a single unit of agent work within a UnitTask.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubTask {
    /// Unique identifier.
    pub id: Uuid,
    /// The parent unit task ID.
    pub unit_task_id: Uuid,
    /// The type of work this subtask performs.
    pub task_type: SubTaskType,
    /// The prompt given to the agent for this subtask.
    pub prompt: String,
    /// Current status of this subtask.
    pub status: SubTaskStatus,
    /// Whether plan mode is enabled for this subtask.
    pub plan_mode_enabled: bool,
    /// The action type this subtask is addressing, if any.
    pub target_action_type: Option<ActionType>,
    /// The commit SHA this subtask starts from.
    pub base_commit_sha: Option<String>,
    /// The latest commit SHA produced by this subtask.
    pub head_commit_sha: Option<String>,
    /// Commits generated by agent sessions in this subtask.
    pub generated_commits: Vec<GeneratedCommit>,
    /// When this record was created.
    pub created_at: DateTime<Utc>,
    /// When this record was last updated.
    pub updated_at: DateTime<Utc>,
}

impl SubTask {
    /// Creates a new subtask.
    pub fn new(unit_task_id: Uuid, task_type: SubTaskType, prompt: impl Into<String>) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            unit_task_id,
            task_type,
            prompt: prompt.into(),
            status: SubTaskStatus::Queued,
            plan_mode_enabled: false,
            target_action_type: None,
            base_commit_sha: None,
            head_commit_sha: None,
            generated_commits: Vec::new(),
            created_at: now,
            updated_at: now,
        }
    }

    /// Enables plan mode for this subtask.
    pub fn with_plan_mode(mut self) -> Self {
        self.plan_mode_enabled = true;
        self
    }

    /// Sets the target action type for this subtask.
    pub fn with_target_action_type(mut self, action_type: ActionType) -> Self {
        self.target_action_type = Some(action_type);
        self
    }

    /// Sets the base commit SHA for this subtask.
    pub fn with_base_commit_sha(mut self, sha: impl Into<String>) -> Self {
        self.base_commit_sha = Some(sha.into());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_unit_task_creation() {
        let workspace_id = Uuid::new_v4();
        let repo_group_id = Uuid::new_v4();
        let task = UnitTask::new(
            workspace_id,
            repo_group_id,
            "Fix the bug",
            "Please fix the authentication bug in the login flow",
        )
        .with_branch_name("fix/auth-bug");

        assert_eq!(task.workspace_id, workspace_id);
        assert_eq!(task.repository_group_id, repo_group_id);
        assert_eq!(task.title, "Fix the bug");
        assert_eq!(task.branch_name, Some("fix/auth-bug".to_string()));
        assert_eq!(task.status, UnitTaskStatus::Queued);
        assert!(task.action_types.is_empty());
    }

    #[test]
    fn test_subtask_creation() {
        let unit_task_id = Uuid::new_v4();
        let subtask = SubTask::new(
            unit_task_id,
            SubTaskType::InitialImplementation,
            "Implement the feature",
        )
        .with_plan_mode()
        .with_target_action_type(ActionType::PlanApprovalRequired);

        assert_eq!(subtask.unit_task_id, unit_task_id);
        assert_eq!(subtask.task_type, SubTaskType::InitialImplementation);
        assert_eq!(subtask.status, SubTaskStatus::Queued);
        assert!(subtask.plan_mode_enabled);
        assert_eq!(
            subtask.target_action_type,
            Some(ActionType::PlanApprovalRequired)
        );
    }
}
